spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bakery_ingredients_db
    username: postgres
    password: postgres
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
